services:
  - type: web
    name: biology-slides
    env: node
    buildCommand: npm install --ignore-scripts && npm run build
    startCommand: npm run sync
    envVars:
      - key: NODE_ENV
        value: production
